
export const PERSONAL_INFO = [
  { label: 'Nama Lengkap', value: 'Muhammad Razzan Firdaus' },
  { label: 'Tempat, Tgl Lahir', value: 'Bogor, 13 Juli 2009' },
  { label: 'Jenis Kelamin', value: 'Laki-laki' },
  { label: 'Kewarganegaraan', value: 'Indonesia' },
  { label: 'Agama', value: 'Islam' },
];

export const SOCIAL_INFO = [
  { label: 'Email', value: 'muhammadrazzan1329@gmail.com' },
  { label: 'WhatsApp', value: '+62 895-3213-84487' },
  { label: 'Instagram', value: '@rzann4e' },
  { label: 'GitHub', value: 'MuhammadRazzanFirdaus' },
  { label: 'LinkedIn', value: 'Muhammad Razzan Firdaus' },
];

export const HARD_SKILLS = [
  { name: 'HTML & CSS', pct: 90 },
  { name: 'JavaScript', pct: 70 },
  { name: 'UI / UX Design', pct: 65 },
  { name: 'Figma', pct: 65 },
  { name: 'Git & GitHub', pct: 80 },
  { name: 'PHP', pct: 90 },
  { name: 'Database', pct: 60 },
];

export const SOFT_SKILLS = [
  'Pemecahan Masalah',
  'Komunikasi Efektif',
  'Kerja Tim',
  'Manajemen Waktu',
  'Perhatian Detail',
  'Kreativitas',
  'Adaptabilitas',
  'Inisiatif',
  'Kemauan Belajar',
  'Organisasi',
  'Ketangguhan',
  'Berpikir Kritis',
];

export const EDUCATION = [
  {
    id: 1,
    year: '2015 — 2018',
    title: 'Sekolah Dasar Negeri',
    inst: 'SDN Megamendung 01 · Bogor, Indonesia',
    desc: 'Menempuh pendidikan sekolah dasar di sekolah ini dan mencapai ranking 3 pada setiap kenaikan kelas namun pada kelas 4 saya pindah sekolah.',
  },
  {
    id: 2,
    year: '2019 — 2021',
    title: 'Sekolah Dasar Negeri',
    inst: 'SDN Cipayung Girang 03 · Bogor, Indonesia',
    desc: 'Melanjutkan pendidikan sekolah dasar di sekolah ini dan menjadi lulusan terbaik pada angkatan saat itu.',
  },
  {
    id: 3,
    year: '2022 — 2024',
    title: 'Sekolah Menengah Pertama Negeri',
    inst: 'SMPN Megamendung 01 · Bogor, Indonesia',
    desc: 'Melanjutkan pendidikan sekolah menengah pertama dan disinilah saya mulai mengenal dan mempelajari dasar komputer.',
  },
  {
    id: 4,
    year: '2025 - Sekarang',
    title: 'Sekolah Menengah Kejuruan',
    inst: 'SMK Wikrama Bogor · Bogor, Indonesia',
    desc: 'Disinilah saya memulai jurnal baru saya dengan memperdalam mengenai ilmu pemrograman.',
  },
  {
    id: 5,
    year: 'Ketika Allah Meridhoi',
    title: 'Perguruan Tinggi',
    inst: 'Institut Teknologi Bandung · Bandung, Indonesia',
    desc: 'Saya sangat bermimpi suatu saat nanti bisa melanjutkan pendidikan saya ke perguruan tinggi di universitas ini.',
  },
];

export const GALLERY_ITEMS = [
  {
    id: 1,
    cat: 'project',
    wide: true,
    icon: '/project.jpeg',
    year: '2024',
    title: 'Beberapa project yang sudah saya handle',
    desc: 'Tempat dimana semua project saya didokumentasikan dan tempat dimana saya bisa mengetahui sejauh mana skill saya sudah berkembang.',
    stack: ['HTML', 'CSS', 'JavaScript', 'PHP', "MYSQL", 'PostgreSQL'],
    url: 'https://github.com/MuhammadRazzanFirdaus',
    overlayText: 'Buka Proyek →',
  },
  {
    id: 2,
    cat: 'certificate',
    wide: false,
    icon: '/Belajar Back-End Pemula dengan JavaScript.png',
    year: '2025',
    title: 'Belajar Back-End Pemula dengan JavaScript',
    desc: 'Dicoding Indonesia — Belajar Back-End Pemula dengan JavaScript.',
    stack: ['Dicoding'],
    img: 'https://placehold.co/900x640/1e1e1e/555?text=Sertifikat+Web+Dev',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ini ditujukan untuk individu yang ingin melangkah menjadi seorang Back-End Developer dengan standar kompetensi internasional milik AWS. Di akhir kelas, siswa dapat membuat RESTful API sederhana secara mandiri untuk mendukung fungsionalitas suatu aplikasi.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 3,
    cat: 'certificate',
    wide: false,
    icon: '/Belajar Dasar Cloud dan Gen AI di AWS.png',
    year: '2025',
    title: 'Belajar Dasar Cloud dan Gen AI di AWS',
    desc: 'Dicoding Indonesia — Belajar Dasar Cloud dan Gen AI di AWS.',
    stack: ['Dicoding'],
    img: 'https://placehold.co/900x640/1e1e1e/555?text=Sertifikat+Web+Dev',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ditujukan bagi pemula yang ingin memulai karirnya di bidang cloud computing dengan mengacu pada standar kompetensi internasional milik AWS. Diakhir kelas, siswa dapat memahami AWS Cloud dengan segala jenis layanan, infrastruktur global, hingga harganya.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 5,
    cat: 'certificate',
    wide: true,
    icon: '/Belajar Membuat Aplikasi Web dengan React.png',
    year: '2025',
    title: 'Belajar Membuat Aplikasi Web dengan React',
    desc: 'Dicoding Indonesia — Belajar Membuat Aplikasi Web dengan React.',
    stack: ['Dicoding'],
    img: 'https://placehold.co/900x640/1e1e1e/555?text=Sertifikat+Web+Dev',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ini ditujukan untuk seorang Front-End Web Developer yang ingin mengembangkan website yang komponen UI-nya reusable, deklaratif, dan bersifat reaktif terhadap perubahan data. Di akhir kelas ini, siswa dapat membuat aplikasi web dengan React yang memanfaatkan functional component, stateful component, dan controlled component.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 6,
    cat: 'certificate',
    wide: false,
    icon: '/Pengenalan ke Logika Pemrograman (Programming Logic 101).png',
    year: '2025',
    title: 'Pengenalan ke Logika Pemrograman (Programming Logic 101)',
    desc: 'Dicoding Indonesia — Pengenalan ke Logika Pemrograman (Programming Logic 101).',
    stack: ['Dicoding'],
    img: 'https://placehold.co/900x640/1e1e1e/555?text=Sertifikat+Web+Dev',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ditujukan bagi pemula yang ingin mulai belajar logika pada bidang pemrograman dengan mengacu pada standar industri. Di akhir kelas, siswa dapat memahami logika pemrograman dasar dan menerapkannya dalam pemecahan masalah yang ada di bidang pekerjaan Software Developer.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 7,
    cat: 'certificate',
    wide: false,
    icon: '/Belajar Membuat Front-End Web untuk Pemula.png',
    year: '2025',
    title: 'Belajar Membuat Front-End Web untuk Pemula',
    desc: 'Dicoding Indonesia — Belajar Membuat Front-End Web untuk Pemula.',
    stack: ['Dicoding'],
    img: 'https://placehold.co/900x640/1e1e1e/555?text=Sertifikat+Web+Dev',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ini ditujukan untuk seorang Front-End Web Developer yang ingin mengembangkan website yang memiliki fungsionalitas lebih daripada hanya media informasi saja, sesuai dengan standar industri. Di akhir kelas, siswa dapat membuat aplikasi front-end web yang interaktif serta memiliki fitur penyimpanan menggunakan web storage.',
    overlayText: 'Lihat Sertifikat',
  }
];
