
export const PERSONAL_INFO = [
  { label: 'Nama Lengkap', value: 'Muhammad Razzan Firdaus' },
  { label: 'Tempat, Tgl Lahir', value: 'Bogor, 13 Juli 2009' },
  { label: 'Jenis Kelamin', value: 'Laki-laki' },
  { label: 'Kewarganegaraan', value: 'Indonesia' },
  { label: 'Agama', value: 'Islam' },
];

export const SOCIAL_INFO = [
  { label: 'Email', value: 'muhammadrazzan1329@gmail.com' },
  { label: 'WhatsApp', value: '+62 895-3213-84487' },
  { label: 'Instagram', value: '@rzann4e' },
  { label: 'GitHub', value: 'MuhammadRazzanFirdaus' },
  { label: 'LinkedIn', value: 'Muhammad Razzan Firdaus' },
];

export const HARD_SKILLS = [
  { name: 'HTML & CSS', pct: 90 },
  { name: 'JavaScript', pct: 70 },
  { name: 'UI / UX Design', pct: 65 },
  { name: 'Figma', pct: 65 },
  { name: 'Git & GitHub', pct: 80 },
  { name: 'PHP', pct: 90 },
  { name: 'Database', pct: 60 },
];

export const SOFT_SKILLS = [
  'Pemecahan Masalah',
  'Komunikasi Efektif',
  'Kerja Tim',
  'Manajemen Waktu',
  'Perhatian Detail',
  'Kreativitas',
  'Adaptabilitas',
  'Inisiatif',
  'Kemauan Belajar',
  'Organisasi',
  'Ketangguhan',
  'Berpikir Kritis',
];

export const EDUCATION = [
  {
    id: 1,
    year: '2015 — 2018',
    title: 'Sekolah Dasar Negeri',
    inst: 'SDN Megamendung 01 · Bogor, Indonesia',
    desc: 'Menempuh pendidikan sekolah dasar di sekolah ini dan mencapai ranking 3 pada setiap kenaikan kelas namun pada kelas 4 saya pindah sekolah.',
  },
  {
    id: 2,
    year: '2019 — 2021',
    title: 'Sekolah Dasar Negeri',
    inst: 'SDN Cipayung Girang 03 · Bogor, Indonesia',
    desc: 'Melanjutkan pendidikan sekolah dasar di sekolah ini dan menjadi lulusan terbaik pada angkatan saat itu.',
  },
  {
    id: 3,
    year: '2022 — 2024',
    title: 'Sekolah Menengah Pertama Negeri',
    inst: 'SMPN Megamendung 01 · Bogor, Indonesia',
    desc: 'Melanjutkan pendidikan sekolah menengah pertama dan disinilah saya mulai mengenal dan mempelajari dasar komputer.',
  },
  {
    id: 4,
    year: '2025 - Sekarang',
    title: 'Sekolah Menengah Kejuruan',
    inst: 'SMK Wikrama Bogor · Bogor, Indonesia',
    desc: 'Disinilah saya memulai jurnal baru saya dengan memperdalam mengenai ilmu pemrograman.',
  }
];

export const GALLERY_ITEMS = [
  {
    id: 1,
    cat: 'project',
    wide: true,
    icon: '/trashedu.png',
    year: '2024',
    title: 'TrashEdu (Trash Educate)',
    desc: 'Platform yang membantu menyebarluaskan informasi dan pembelajaran mengenai pentingnya mengelola sampah melalui platform yang menyenangkan karena dipadukan dengan sedikit gamifikasi',
    stack: ['Laravel', 'MySQL', 'Bootstrap'],
    url: 'https://github.com/MuhammadRazzanFirdaus/TrashEdu',
    overlayText: 'Buka Proyek →',
  },
  {
    id: 2,
    cat: 'certificate',
    wide: false,
    icon: '/Belajar Back-End Pemula dengan JavaScript.png',
    year: '2025',
    title: 'Belajar Back-End Pemula dengan JavaScript',
    desc: 'Dicoding Indonesia — Belajar Back-End Pemula dengan JavaScript.',
    stack: ['Dicoding'],
    img: '/Belajar Back-End Pemula dengan JavaScript.png',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ini ditujukan untuk individu yang ingin melangkah menjadi seorang Back-End Developer dengan standar kompetensi internasional milik AWS. Di akhir kelas, siswa dapat membuat RESTful API sederhana secara mandiri untuk mendukung fungsionalitas suatu aplikasi.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 3,
    cat: 'project',
    wide: false,
    icon: '/fingo.png',
    year: '2025',
    title: 'FinGo (Financial Goals)',
    desc: 'Platform yang membantu masyarakat memantau dan mengelola pengeluaran harian/mingguan dan bulanan sekaligus mempermudah masyarakat dalam menabung',
    stack: ['Laravel', 'React.js', 'MySQL', 'TailwindCss'],
    url: 'https://fingo-financialgoals.vercel.app',
    overlayText: 'Buka Proyek →',
  },
  {
    id: 4,
    cat: 'certificate',
    wide: true,
    icon: '/Belajar Dasar Cloud dan Gen AI di AWS.png',
    year: '2025',
    title: 'Belajar Dasar Cloud dan Gen AI di AWS',
    desc: 'Dicoding Indonesia — Belajar Dasar Cloud dan Gen AI di AWS.',
    stack: ['Dicoding'],
    img: '/Belajar Dasar Cloud dan Gen AI di AWS.png',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ditujukan bagi pemula yang ingin memulai karirnya di bidang cloud computing dengan mengacu pada standar kompetensi internasional milik AWS. Diakhir kelas, siswa dapat memahami AWS Cloud dengan segala jenis layanan, infrastruktur global, hingga harganya.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 5,
    cat: 'project',
    wide: false,
    icon: '/brest.png',
    year: '2025',
    title: 'BRest (Bogor Forest)',
    desc: 'Platform yang membantu menyediakan informasi mengenai berbagai macam flora dan fauna yang ada di ruang lingkup Bogor',
    stack: ['Laravel', 'MySQL', 'Bootstrap'],
    url: 'https://forest.smkwikrama.sch.id',
    overlayText: 'Buka Proyek →',
  },
  {
    id: 6,
    cat: 'certificate',
    wide: false,
    icon: '/Belajar Membuat Aplikasi Web dengan React.png',
    year: '2025',
    title: 'Belajar Membuat Aplikasi Web dengan React',
    desc: 'Dicoding Indonesia — Belajar Membuat Aplikasi Web dengan React.',
    stack: ['Dicoding'],
    img: '/Belajar Membuat Aplikasi Web dengan React.png',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ini ditujukan untuk seorang Front-End Web Developer yang ingin mengembangkan website yang komponen UI-nya reusable, deklaratif, dan bersifat reaktif terhadap perubahan data. Di akhir kelas ini, siswa dapat membuat aplikasi web dengan React yang memanfaatkan functional component, stateful component, dan controlled component.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 7,
    cat: 'project',
    wide: true,
    icon: '/tixid.png',
    year: '2025',
    title: 'TIX ID (Clone)',
    desc: 'Membuat ulang website TIX ID dengan styling pribadi tetapi membuat fungsi yang mirip seperti website TIX ID',
    stack: ['Laravel', 'MySQL', 'Bootstrap'],
    url: 'https://github.com/MuhammadRazzanFirdaus/App_Tixid',
    overlayText: 'Buka Proyek →',
  },
  {
    id: 8,
    cat: 'certificate',
    wide: false,
    icon: '/Pengenalan ke Logika Pemrograman (Programming Logic 101).png',
    year: '2025',
    title: 'Pengenalan ke Logika Pemrograman (Programming Logic 101)',
    desc: 'Dicoding Indonesia — Pengenalan ke Logika Pemrograman (Programming Logic 101).',
    stack: ['Dicoding'],
    img: '/Pengenalan ke Logika Pemrograman (Programming Logic 101).png',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ditujukan bagi pemula yang ingin mulai belajar logika pada bidang pemrograman dengan mengacu pada standar industri. Di akhir kelas, siswa dapat memahami logika pemrograman dasar dan menerapkannya dalam pemecahan masalah yang ada di bidang pekerjaan Software Developer.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 9,
    cat: 'project',
    wide: false,
    icon: '/company.png',
    year: '2025',
    title: 'Company Profile',
    desc: 'Membuat website Company Profile yang bertemakan mobil porsche',
    stack: ['Laravel', 'Bootstrap'],
    url: 'https://github.com/MuhammadRazzanFirdaus/Company_Profile',
    overlayText: 'Buka Proyek →',
  },
  {
    id: 10,
    cat: 'certificate',
    wide: true,
    icon: '/Belajar Membuat Front-End Web untuk Pemula.png',
    year: '2025',
    title: 'Belajar Membuat Front-End Web untuk Pemula',
    desc: 'Dicoding Indonesia — Belajar Membuat Front-End Web untuk Pemula.',
    stack: ['Dicoding'],
    img: '/Belajar Membuat Front-End Web untuk Pemula.png',
    issuer: 'Dicoding Indonesia · 2025',
    certDesc: 'Kelas ini ditujukan untuk seorang Front-End Web Developer yang ingin mengembangkan website yang memiliki fungsionalitas lebih daripada hanya media informasi saja, sesuai dengan standar industri. Di akhir kelas, siswa dapat membuat aplikasi front-end web yang interaktif serta memiliki fitur penyimpanan menggunakan web storage.',
    overlayText: 'Lihat Sertifikat',
  },
  {
    id: 11,
    cat: 'project',
    wide: false,
    icon: '/PrayerTime.png',
    year: '2025',
    title: 'PrayerTime',
    desc: 'Website yang menampilkan data jam sholat di berbagai daerah yang ada di Indonesia secara real time',
    stack: ['React', 'TailwindCSS'],
    url: 'https://github.com/MuhammadRazzanFirdaus/PrayerTime',
    overlayText: 'Buka Proyek →',
  },
  {
    id: 12,
    cat: 'certificate',
    wide: false,
    icon: '/BNSP.png',
    year: '2025',
    title: 'Junior Web Programmer',
    desc: 'Short Course yang diadakan oleh Telkom DigiUp dalam path ReactJs dan sertifikat yang diterbitkan oleh BNSP.',
    stack: ['BNSP & Telkom DigiUp'],
    img: '/BNSP.png',
    issuer: 'BNSP · 2025',
    certDesc: 'Kelas ditujukan bagi pemula yang dinilai kompeten dalam membuat tampilan website menggunakan React.js.',
    overlayText: 'Lihat Sertifikat',
  },
];
